// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemon_Api.Data;

namespace Pokemon_Api.Migrations
{
    [DbContext(typeof(PokemonApiContext))]
    [Migration("20220208194326_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pokemon_Api.Models.Abilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("PokeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PokeId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("Pokemon_Api.Models.Poke", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("Weight")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Poke");
                });

            modelBuilder.Entity("Pokemon_Api.Models.TypesPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long?>("PokeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("PokeId");

                    b.ToTable("TypesPokemon");
                });

            modelBuilder.Entity("Pokemon_Api.Models.Abilities", b =>
                {
                    b.HasOne("Pokemon_Api.Models.Poke", null)
                        .WithMany("Abilities")
                        .HasForeignKey("PokeId");
                });

            modelBuilder.Entity("Pokemon_Api.Models.TypesPokemon", b =>
                {
                    b.HasOne("Pokemon_Api.Models.Poke", null)
                        .WithMany("Type")
                        .HasForeignKey("PokeId");
                });
#pragma warning restore 612, 618
        }
    }
}
